const fortunes = [
    "The fortune you seek is in another cookie",
    "You will live long enough to open many fortune cookies",
    "I am worth a fortune", 
    "Ask your mom instead of a cookie", 
    "Avoid taking unnecessary gambles. Lucky numbers: 00000000001, 00000000101, 11111100010",
    "A program is never less than 90% complete and never more than 95% complete", 
    "Two bytes meet. The first byte asks, ‘Are you ill?’ The second byte replies, ‘No, just feeling a bit off", 
    "You have not failed. You’ve just found 10,000 ways that won’t work", 
    "There is no Ctrl-Z in life",
    "Be vigilant! Bugs hide in codes for the winter!",
    "Sudden lack of strength? Coffee Point's black elixir will help you!", 
    "A water source will do \"brrrrr\". Be careful!", 
    "The elevator will go up. Or down",  
    "Another day, another Daily. Be agile!", 
    "It will be windy. Wear a hat, protect your main work tool", 
    "You will be rich. The paycheck is coming soon", 
    "You'll be hungry at lunchtime", 
    "Soon you will have a great trip... to the office", 
    "You will meet a great EPAMer today. In the mirror", 
    "Someone will want to guess your thoughts. Wear a hat on call", 
    "The stars say you have a teleportation power today. Just get in the elevator", 
    "Tomorrow will be Friday", 
    "Roses are red, EPAM is blue. You will hear today: Hi, how are you?", 
    "If you use Ctrl+C and Ctrl+V today, there will be twins waiting for you at home", 
    "It will be dark today!", 
    "\"Don't refuse this candy!\" - Tooth Fairy", 
    "A great moment of meditation after lunch awaits you. Just close your eyes and mute your laptop", 
    "Horoscope for today: coffee will run out", 
    "If you say to the mirror 3 times \"EPAM\", you will hear \"hey, dude, you ok?\"",
    "Don't run too much! You will loose something! (eg.: some kilos)",
    "Tomorrow you'll wake up older than today", 
    "Get ready for a life-changing event!",
    "You will be hungry again in one hour", 
    "Wisdom comes from experience", 
    "You can never be certain of success, but you can be certain of failure, if you never try", 
    "Sorry, you don't have permission to read this fortune cookie", 
    "Do or do not submit a ticket, there is no try", 
    "A lengthy journey down an internet rabbit hole begins with a single click", 
    "Today, for once, no one will bug you about fixing their computer", 
    "This is one cookie that can't be deleted", 
    "A system reboot is in your future. Of this I am certain", 
    "Your IT talents will not go unnoticed ... by friends in need of tech support",
    "404: Fortune not found. Please contact your system administrator", 
    "Clippy says: It looks like you're eating a cookie. Would you like help?", 
    "If you build it, users will find a way to break it", 
    "Error: This fortune requires cookies to be enabled before you proceed",  
    "Many facepalms experienced ultimately make you a stronger person", 
    "Not testing your backups is like asking for disaster", 
    "Life in IT isn't always a PICNIC. It can also be a PEBCAK",  
    "True happiness in IT is an empty ticket queue", 
    "How many of you believe in psycho-kinesis? Raise my hand. 52. Success will be yours... Happy install", 
    "Error: Cookies not supported",
    "Thought of the day: Where does the Help Desk go for help? ",
    "There will be an Error 404 in your lunchbox after lunch",
    "Photocopier will be malicious today. Don't let it know you're in a hurry", 
    "In 29 days you'll get a gift. Many gifts",
    "Everything not saved will be lost",
    "The Princess is in another castle!",
    "When making New Year's resolutions avoid 800 x 600",
    "Press F5 for your next fortune",
    "A clean disk is a sign of a sick computer", 
    "Treat life like interfaces - refresh and renew as necessary",
    "Delete your browser history. Just do it",
    "You will hear from a long lost %USERNAME%", 
    "Your brain needs to deal with cookies - take a nap!", 
    "Your skills are needed by others at this time", 
    "You would do well in the field of computer technology", 
    "You would do well in the field of HR", 
    "“People’s lives don’t end when they die, it ends when they lose faith.”  – Itachi Uchiha (Naruto)",
    "“Power comes in response to a need, not a desire. You have to create that need.” – Goku (Dragon Ball Z)",
    "“Try not. Do or do not. There is no try.” —Yoda",
    "\"It's a me! Mario!\" - Mario", 
    "“The ability to speak does not make you intelligent.” —Qui-Gon Jinn",
    "\"You were the chosen one!\" —Obi-Wan Kenob",
    "“In my experience, there’s no such thing as luck.” —Obi-Wan Kenob",
    "“Women always figure out the truth. Always.” —Han Solo", 
    "“I find your lack of faith disturbing.” —Darth Vader" 
];